name:                repeater-bot
version:             0.1.0.0
github:              "githubuser/repeater-bot"
license:             BSD3
author:              "Oleg Romashin"
maintainer:          "Odeyaloleg@gmail.com"
copyright:           "2020 Oleg Romashin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/repeater-bot#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- http-conduit
- http-client
- http-types
- bytestring
- containers
- async
- wai
- warp
- streaming-commons
- mtl
- QuickCheck

library:
  source-dirs: src

executables:
  repeater-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repeater-bot

tests:
  repeater-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repeater-bot
